# FLUX.1-dev Fine-Tuning Configuration
job: extension
config:
  name: "flux_finetuned_model"
  process:
    - type: 'sd_trainer'
      training_folder: "/content/output"
      performance_log_every: 100
      device: cuda:0
      trigger_word: "marketmind"  # Change this to your desired trigger word
      network:
        type: "lora"
        linear: 32
        linear_alpha: 32
      save:
        dtype: float16
        save_every: 250
        max_step_saves_to_keep: 5
        push_to_hub: false
  datasets:
    - folder_path: "/content/drive/MyDrive/AI/processed_data/all_images"         # Path to your image folder
      caption_folder: "/content/drive/MyDrive/AI/processed_data/captions"    # Path to your caption folder
      caption_ext: "txt"
      caption_dropout_rate: 0.02
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution: [512]
  train:
    batch_size: 1
    steps: 2000
    gradient_accumulation_steps: 1
    train_unet: false
    train_text_encoder: false
    gradient_checkpointing: true
    noise_scheduler: "flowmatch"
    optimizer: "adamw8bit"
    lr: 1e-4
  ema_config:
    use_ema: true
    ema_decay: 0.99
  dtype: bf16
  model:
    name_or_path: "black-forest-labs/FLUX.1-dev"
    is_flux: true
    quantize: true
  sample:
    sampler: "flowmatch"
    sample_every: 250
    width: 512
    height: 512
    prompts:
      - "[marketmind] a vibrant social media ad poster promoting a summer sale, featuring bold text and colorful graphics"
      - "[marketmind] a sleek, modern ad poster for a tech product launch, with minimalist design and dynamic lighting"
      - "[marketmind] an eye-catching social media poster for a new café opening, showcasing cozy vibes and appetizing food photography"
    neg: "blurry, low quality, distorted"
    seed: 42
    walk_seed: true
    guidance_scale: 4
    sample_steps: 20
meta:
  name: "flux_finetuned_model"
  version: '1.0'
