config:
  name: my_first_flux_lora_v1
  process:
  - datasets:
    - cache_latents_to_disk: true
      caption_dropout_rate: 0.05
      caption_ext: txt
      folder_path: /content/drive/MyDrive/AI/processed_data2
      resolution:
      - 512
      shuffle_tokens: false
    device: cuda:0
    model:
      is_flux: true
      name_or_path: black-forest-labs/FLUX.1-dev
      quantize: true
    network:
      linear: 16
      linear_alpha: 16
      type: lora
    performance_log_every: 250
    sample:
      guidance_scale: 4
      height: 512
      neg: ''
      prompts:
      - '[marketmind] a vibrant social media ad poster promoting a summer sale, featuring
        bold text and colorful graphics'
      - '[marketmind] a sleek, modern ad poster for a tech product launch, with minimalist
        design and dynamic lighting'
      - "[marketmind] an eye-catching social media poster for a new caf\xE9 opening,\
        \ showcasing cozy vibes and appetizing food photography"
      sample_every: 250
      sample_steps: 20
      sampler: flowmatch
      seed: 42
      walk_seed: true
      width: 512
    save:
      dtype: float16
      max_step_saves_to_keep: 4
      push_to_hub: false
      save_every: 250
    train:
      batch_size: 1
      dtype: bf16
      ema_config:
        ema_decay: 0.99
        use_ema: true
      gradient_accumulation_steps: 1
      gradient_checkpointing: true
      lr: 1e-4
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      performance_log_every: 250
      steps: 2000
      train_text_encoder: false
      train_unet: false
    training_folder: /content/output
    trigger_word: marketmind
    type: sd_trainer
job: extension
meta:
  name: '[name]'
  version: '1.0'
