---
# NOTE!! THIS IS CURRENTLY EXPERIMENTAL AND UNDER DEVELOPMENT. SOME THINGS WILL CHANGE
job: extension
config:
  # this name will be the folder and filename name
  name: "my_first_sd3l_lora_v1"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "/content/output"
      # uncomment to see performance stats in the terminal every N steps
      performance_log_every: 250
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "marketmind"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 # precision to save
        save_every: 250 # save every this many steps
        max_step_saves_to_keep: 4 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
        # You can either set up a HF_TOKEN env variable or you'll be prompted to log-in         
#       hf_repo_id: your-username/your-model-slug
#       hf_private: true #whether the repo is private or public
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "/content/drive/MyDrive/AI/processed_data2"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [512] 
      train:
        batch_size: 1
        steps: 2000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # May not fully work with SD3 yet
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch"
        timestep_type: "linear" # linear or sigmoid
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for sd3, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "stabilityai/stable-diffusion-3.5-large"
        is_v3: true
        quantize: true  # run 8bit mixed precision
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 250 # sample every this many steps
        width: 512
        height: 512
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
#          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"\
          - "[marketmind] a vibrant social media ad poster promoting a summer sale, featuring bold text and colorful graphics"
          - "[marketmind] a sleek, modern ad poster for a tech product launch, with minimalist design and dynamic lighting"
          - "[marketmind] an eye-catching social media poster for a new café opening, showcasing cozy vibes and appetizing food photography"
          - "[marketmind] an Instagram ad poster for a skincare brand, featuring a close-up of a glowing face with soft natural light, minimalist pastel background, elegant text overlay that says 'Glow Naturally ✨ New Skincare Essentials – Link in Bio'"
          - "[marketmind] a trendy Instagram ad poster for a streetwear brand, showing a stylish young adult leaning against a graffiti wall, urban color tones (neon and dark contrast), bold, edgy text saying 'Own The Streets 🚀 Limited Drop Available Now'"
          - "[marketmind] a cozy and inviting poster for a coffee shop's autumn special, showing a hand holding a steaming cup with falling leaves around, warm brown and orange tones, and charming handwritten text saying 'Pumpkin Spice Season – Sip the Magic'"
          - "[marketmind] a colorful social media ad poster for a fashion brand's spring collection, featuring a model in a flowy dress among blooming flowers, pastel tones, and bold text that says 'Blossom Into Style – Shop Now'"
        neg: ""  
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 25
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
